# Generated by Django 4.0 on 2022-01-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
