# Generated by Django 4.0 on 2022-01-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_customers_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='mobile',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
